# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: minimal

cache: cargo

branches:
    only:
        - master
        - develop
        - hotfox/fix-ci 

env:
    global:
        - RUST_BACKTRACE=1
    matrix:
        - RUST_TOOLCHAIN=stable TARGET=rustfmt
        - RUST_TOOLCHAIN=nightly TARGET=wasm
        - RUST_TOOLCHAIN=nightly TARGET=native

before_install:
    # Check how much space we've got on this machine.
    - df -h

script:
    # The stage of building  
    - .maintain/ci/build_script.sh
    # The stage of test darwinia customize model
    - .maintain/ci/darwinia_test_script.sh
    # The stage of test all modules including substrates
    - .maintain/ci/test_script.sh

after_script:
    # Check how much free disk space left after the build
    - df -h
