# Request an environment that provides sudo (that goes with larger containers)
# and a minimal language environment.
sudo: true
language: minimal

cache: cargo

branches:
    only:
        - master
        - develop
        - hotfox/fix-ci 

env:
    global:
        - RUST_BACKTRACE=1
    matrix:
        - RUST_TOOLCHAIN=stable TARGET=rustfmt
        - RUST_TOOLCHAIN=nightly TARGET=wasm
        - RUST_TOOLCHAIN=nightly TARGET=native

before_install:
    # Check how much space we've got on this machine.
    - df -h

script:
    # The stage of building  
    - echo 'Building...' && echo -en 'travis_fold:start:build\\r'
    - .maintain/ci/build_script.sh
    - echo -en 'travis_fold:end:build\\r'

    # The stage of test darwinia customize model
    - echo 'Test Darwinia Modules...' && echo -en 'travis_fold:start:darwinia_test\\r'
    - .maintain/ci/darwinia_test_script.sh
    - echo -en 'travis_fold:end:darwinia_test\\r'

    # The stage of test all modules including substrates
    - echo 'Test All Modules...' && echo -en 'travis_fold:start:all_test\\r'
    - .maintain/ci/test_script.sh
    - echo -en 'travis_fold:end:all_test\\r'

after_script:
    # Check how much free disk space left after the build
    - df -h
